version: "3.2"
services:
  python:
    build: .  #current directory
    stdin_open: true #docker run -i
    tty: true  #docker run -t
    #allows you to login to container
    volumes:
      - .:/home/myuser    #runs program under unprivelged user (for security)
